const epidemiologicalData = [
  { country: "India", year: 1994, cases: 850, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 1994, cases: 1200, virus_type: "variola_major", region: "Africa" },
  { country: "Indonesia", year: 1994, cases: 420, virus_type: "variola_major", region: "Asia" },
  { country: "Bangladesh", year: 1994, cases: 380, virus_type: "variola_minor", region: "Asia" },
  { country: "Pakistan", year: 1994, cases: 950, virus_type: "variola_major", region: "Asia" },
  { country: "Brazil", year: 1994, cases: 280, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 1994, cases: 620, virus_type: "variola_major", region: "Africa" },
  { country: "Kenya", year: 1994, cases: 340, virus_type: "variola_minor", region: "Africa" },
  { country: "China", year: 1994, cases: 490, virus_type: "variola_major", region: "Asia" },
  { country: "DRC", year: 1994, cases: 710, virus_type: "variola_major", region: "Africa" },

  { country: "India", year: 1999, cases: 340, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 1999, cases: 520, virus_type: "variola_minor", region: "Africa" },
  { country: "Indonesia", year: 1999, cases: 180, virus_type: "variola_major", region: "Asia" },
  { country: "Brazil", year: 1999, cases: 95, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 1999, cases: 240, virus_type: "variola_major", region: "Africa" },
  { country: "Pakistan", year: 1999, cases: 380, virus_type: "variola_major", region: "Asia" },
  { country: "Kenya", year: 1999, cases: 120, virus_type: "variola_minor", region: "Africa" },
  { country: "Bangladesh", year: 1999, cases: 150, virus_type: "variola_minor", region: "Asia" },
  { country: "DRC", year: 1999, cases: 290, virus_type: "variola_major", region: "Africa" },
  { country: "Tanzania", year: 1999, cases: 85, virus_type: "variola_minor", region: "Africa" },

  { country: "India", year: 2004, cases: 120, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 2004, cases: 180, virus_type: "variola_minor", region: "Africa" },
  { country: "Brazil", year: 2004, cases: 35, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 2004, cases: 75, virus_type: "variola_major", region: "Africa" },
  { country: "Bangladesh", year: 2004, cases: 50, virus_type: "variola_minor", region: "Asia" },
  { country: "Indonesia", year: 2004, cases: 45, virus_type: "variola_major", region: "Asia" },
  { country: "DRC", year: 2004, cases: 95, virus_type: "variola_major", region: "Africa" },
  { country: "Kenya", year: 2004, cases: 35, virus_type: "variola_minor", region: "Africa" },
  { country: "Pakistan", year: 2004, cases: 110, virus_type: "variola_major", region: "Asia" },
  { country: "Ghana", year: 2004, cases: 25, virus_type: "variola_minor", region: "Africa" },

  { country: "India", year: 2009, cases: 35, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 2009, cases: 45, virus_type: "variola_minor", region: "Africa" },
  { country: "Brazil", year: 2009, cases: 12, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 2009, cases: 22, virus_type: "variola_major", region: "Africa" },
  { country: "Bangladesh", year: 2009, cases: 15, virus_type: "variola_minor", region: "Asia" },
  { country: "Pakistan", year: 2009, cases: 28, virus_type: "variola_major", region: "Asia" },
  { country: "DRC", year: 2009, cases: 32, virus_type: "variola_major", region: "Africa" },
  { country: "Kenya", year: 2009, cases: 10, virus_type: "variola_minor", region: "Africa" },
  { country: "Indonesia", year: 2009, cases: 18, virus_type: "variola_major", region: "Asia" },
  { country: "Tanzania", year: 2009, cases: 8, virus_type: "variola_minor", region: "Africa" },

   { country: "India", year: 2014, cases: 12, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 2014, cases: 15, virus_type: "variola_minor", region: "Africa" },
  { country: "Brazil", year: 2014, cases: 5, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 2014, cases: 8, virus_type: "variola_major", region: "Africa" },
  { country: "Bangladesh", year: 2014, cases: 6, virus_type: "variola_minor", region: "Asia" },
  { country: "Pakistan", year: 2014, cases: 10, virus_type: "variola_major", region: "Asia" },
  { country: "DRC", year: 2014, cases: 11, virus_type: "variola_major", region: "Africa" },
  { country: "Kenya", year: 2014, cases: 4, virus_type: "variola_minor", region: "Africa" },
  { country: "Indonesia", year: 2014, cases: 7, virus_type: "variola_major", region: "Asia" },
  { country: "Uganda", year: 2014, cases: 6, virus_type: "variola_minor", region: "Africa" },

  { country: "India", year: 2019, cases: 5, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 2019, cases: 8, virus_type: "variola_minor", region: "Africa" },
  { country: "Brazil", year: 2019, cases: 2, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 2019, cases: 3, virus_type: "variola_major", region: "Africa" },
  { country: "Bangladesh", year: 2019, cases: 3, virus_type: "variola_minor", region: "Asia" },
  { country: "Pakistan", year: 2019, cases: 4, virus_type: "variola_major", region: "Asia" },
  { country: "DRC", year: 2019, cases: 6, virus_type: "variola_major", region: "Africa" },
  { country: "Kenya", year: 2019, cases: 2, virus_type: "variola_minor", region: "Africa" },
  { country: "Indonesia", year: 2019, cases: 3, virus_type: "variola_major", region: "Asia" },
  { country: "Tanzania", year: 2019, cases: 1, virus_type: "variola_minor", region: "Africa" },

  { country: "India", year: 2024, cases: 2, virus_type: "variola_major", region: "Asia" },
  { country: "Nigeria", year: 2024, cases: 3, virus_type: "variola_minor", region: "Africa" },
  { country: "Brazil", year: 2024, cases: 1, virus_type: "variola_minor", region: "Americas" },
  { country: "Ethiopia", year: 2024, cases: 1, virus_type: "variola_major", region: "Africa" },
  { country: "Bangladesh", year: 2024, cases: 1, virus_type: "variola_minor", region: "Asia" },
  { country: "Pakistan", year: 2024, cases: 2, virus_type: "variola_major", region: "Asia" },
  { country: "DRC", year: 2024, cases: 3, virus_type: "variola_major", region: "Africa" },
  { country: "Kenya", year: 2024, cases: 1, virus_type: "variola_minor", region: "Africa" },
  { country: "Indonesia", year: 2024, cases: 1, virus_type: "variola_major", region: "Asia" },
  { country: "Uganda", year: 2024, cases: 1, virus_type: "variola_minor", region: "Africa" }
  ];

// Coordenadas de países para el mapa
const countryCoordinates = {
    "India": { lat: 20.5937, lng: 78.9629 },
    "Nigeria": { lat: 9.0820, lng: 8.6753 },
    "Indonesia": { lat: -0.7893, lng: 113.9213 },
    "Bangladesh": { lat: 23.6850, lng: 90.3563 },
    "Pakistan": { lat: 30.3753, lng: 69.3451 },
    "Brazil": { lat: -14.2350, lng: -51.9253 },
    "Ethiopia": { lat: 9.1450, lng: 40.4897 },
    "Kenya": { lat: -0.0236, lng: 37.9062 },
    "China": { lat: 35.8617, lng: 104.1954 },
    "DRC": { lat: -4.0383, lng: 21.7587 },
    "Tanzania": { lat: -6.3690, lng: 34.8888 },
    "Ghana": { lat: 7.3697, lng: -5.7432 },
    "Uganda": { lat: 1.3733, lng: 32.2903 }
};
